#!/bin/bash

if [ $LOGNAME == 'stevegt' ]
then
    if ! ./check-svn-st 
    then
        echo "not synced with svn"
        exit 1
    fi
    changeset=$(svn up | tr -d '.' | awk '{print $3}')
    changeset=$(( $changeset + 1 ))
    echo $changeset > revision
    release=$(cat version).$(cat revision)
    echo "def release(): return '$release'" > lib/python/isconf/version.py
    svn ci -m "release $release"
    changeset=$(svn up | tr -d '.' | awk '{print $3}')
    if [ $changeset -ne $(cat revision) ]
    then
        echo "revision not synced with changeset number"
        exit 1
    fi
fi






