#!/bin/bash

if [ $LOGNAME == 'stevegt' ]
then
    # if ! ./check-git-st 
    # then
    #     echo "not committed"
    #     exit 1
    # fi
    release=$(cat version).$(cat revision)
    echo "def release(): return '$release'" > lib/python/isconf/version.py
    git add lib/python/isconf/version.py
    git commit -m "release $release"
    # changeset=$(svn up | tr -d '.' | awk '{print $3}')
    # if [ $changeset -ne $(cat revision) ]
    # then
    #     echo "revision not synced with changeset number"
    #     exit 1
    # fi
fi






