#!/bin/sh 

base=`dirname $0`/..
cd $base
base=$PWD
cd -
PYTHONPATH=$base/lib/python 

# set up network addresses to talk to in addition to UDP broadcast
if hostname | egrep '^test' > /dev/null
then
    IS_NETS=$base/t/nets
fi

# try to use old python for compatibility testing
# python=python2.2
# if ! which python2.2 > /dev/null
# then
#     python=python
# fi

[ -z "$PYTHON" ] && PYTHON=python

coverage=''
if test -n "$COVERAGE"
then
    coverage="$base/t/coverage.py -x"
fi

export PYTHONPATH IS_NETS

$PYTHON $coverage $base/bin/isconf -c $base/t/simple.conf "$@"

