#!/usr/bin/python

import sys

try:
    statsfn = sys.argv[1]
except:
    statsfn = '.pstats'

import pstats
p = pstats.Stats(statsfn)
# p.sort_stats('time').print_stats(10)
p.strip_dirs()
p.sort_stats('cumulative').print_stats(20)
p.print_callers()


